name: CoSSeAShop
main: CoSSeSystem\CoSSeAShop
version: 0.1
api: [2.0.0]
load: POSTWORLD
author: popkechupki
description: Open admin's shop
website: https://github.com/CosmoSunriseServerPluginEditorsTeam/CoSSeAShop
